GET http://localhost:3000/users

###
POST http://localhost:3000/syncc
n
###
POST http://localhost:3000/submit-form
Content-Type: application/json 

{
    "username":"fadoamne", "pass":"USHATA"
}
###

POST http://localhost:3000/users-login
Content-Type: application/json

{
    "username":"gik", "pass":"123"
}